name:                haskii
version:             0.1.0.0
github:              "tkachuk-labs/haskii"
license:             BSD3
author:              "Ilja Tkachuk"
maintainer:          "tkachuk.labs@gmail.com"
copyright:           "2021 Ilja Tkachuk"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Functional, Monadic Ascii-Art.
category:            Data, Text

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tkachuk-labs/haskii#readme>

dependencies:
# foundation
- base >= 4.7 && < 5
- mtl >=2.2 && <2.3
- text >=1.2 && <1.3
- containers >=0.5 && <0.6
- bytestring >=0.10 && <0.11
- lens-simple >=0.1 && <0.2
- rainbow >=0.28 && <0.31
- attoparsec >=0.13 && <0.14
- casing >= 0.1.4 && < 0.2
- directory-tree
- th-lift-instances
- filepath
- directory
- universum
- ghc >= 8.2 && < 8.11
- ghc-paths == 0.1.*
- ghc-source-gen >= 0.4 && < 0.5
# time
- time
- chronos
- unbounded-delays
- retry
# storage
- persistent
- persistent-postgresql
- persistent-template
- persistent-migration
- esqueleto
# logging
- katip
- monad-logger
# web
- wai
- wai-middleware-static-embedded
- warp
- websockets
- replica
- concur-core
- concur-replica
# lens
- lens
- microlens
# bytes and text
- text
# threads
- async
- stm
- resource-pool
# th
- template-haskell
- file-embed
# other
- unliftio
- containers
- envparse
- extra

library:
  source-dirs: Haskii
  default-extensions:
  - NoImplicitPrelude
  - MultiParamTypeClasses
  - LambdaCase
  - OverloadedStrings
  - ScopedTypeVariables
  - DerivingStrategies
  - FlexibleInstances
  - TypeFamilies
  ghc-options:
  # For details on warnings: https://downloads.haskell.org/~ghc/master/users-guide/using-warnings.html
  # Enable all warnings with -Weverything, then disable the ones we don’t care about
  - -Weverything
  - -Werror
  - -Wno-missing-exported-signatures # missing-exported-signatures turns off the more strict -Wmissing-signatures. See https://ghc.haskell.org/trac/ghc/ticket/14794#ticket
  - -Wno-missing-import-lists # Requires explicit imports of _every_ function (e.g. ‘$’); too strict
  - -Wno-missed-specialisations # When GHC can’t specialize a polymorphic function. No big deal and requires fixing underlying libraries to solve.
  - -Wno-all-missed-specialisations # See missed-specialisations
  - -Wno-unsafe # Don’t use Safe Haskell warnings
  - -Wno-safe # Don’t use Safe Haskell warnings
  - -Wno-missing-local-signatures # Warning for polymorphic local bindings; nothing wrong with those.
  - -Wno-monomorphism-restriction # Don’t warn if the monomorphism restriction is used
  dependencies:
  - hspec
  - hspec-wai

executables:
  haskii-exe:
    main: Main.hs
    source-dirs: HaskiiFigletGen
    default-extensions:
    - NoImplicitPrelude
    - MultiParamTypeClasses
    - LambdaCase
    - OverloadedStrings
    - ScopedTypeVariables
    - DerivingStrategies
    - FlexibleInstances
    - TypeFamilies
    ghc-options:
    # For details on warnings: https://downloads.haskell.org/~ghc/master/users-guide/using-warnings.html
    # Enable all warnings with -Weverything, then disable the ones we don’t care about
    - -Weverything
    - -Werror
    - -Wno-missing-exported-signatures # missing-exported-signatures turns off the more strict -Wmissing-signatures. See https://ghc.haskell.org/trac/ghc/ticket/14794#ticket
    - -Wno-missing-import-lists # Requires explicit imports of _every_ function (e.g. ‘$’); too strict
    - -Wno-missed-specialisations # When GHC can’t specialize a polymorphic function. No big deal and requires fixing underlying libraries to solve.
    - -Wno-all-missed-specialisations # See missed-specialisations
    - -Wno-unsafe # Don’t use Safe Haskell warnings
    - -Wno-safe # Don’t use Safe Haskell warnings
    - -Wno-missing-local-signatures # Warning for polymorphic local bindings; nothing wrong with those.
    - -Wno-monomorphism-restriction # Don’t warn if the monomorphism restriction is used
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskii
