{- This file was auto-generated by the haskii-exe program. -}
{-# LANGUAGE NoImplicitPrelude #-}

module Haskii.Figlet.Font (
        Font(..), getFLF
    ) where
import qualified Universum
import qualified Haskii.Figlet.Types
import qualified Haskii.Figlet.Font.Acrobatic
import qualified Haskii.Figlet.Font.Alligator
import qualified Haskii.Figlet.Font.Alligator2
import qualified Haskii.Figlet.Font.Alligator3
import qualified Haskii.Figlet.Font.Alpha
import qualified Haskii.Figlet.Font.AmCAaA01
import qualified Haskii.Figlet.Font.AmCNeko
import qualified Haskii.Figlet.Font.AmCRazor
import qualified Haskii.Figlet.Font.AmCRazor2
import qualified Haskii.Figlet.Font.AmCSlash
import qualified Haskii.Figlet.Font.AmCSlider
import qualified Haskii.Figlet.Font.AmCThin
import qualified Haskii.Figlet.Font.AmCTubes
import qualified Haskii.Figlet.Font.AmCUntitled
import qualified Haskii.Figlet.Font.Arrows
import qualified Haskii.Figlet.Font.Avatar
import qualified Haskii.Figlet.Font.Banner
import qualified Haskii.Figlet.Font.Banner3
import qualified Haskii.Figlet.Font.Banner3D
import qualified Haskii.Figlet.Font.Banner4
import qualified Haskii.Figlet.Font.Barbwire
import qualified Haskii.Figlet.Font.Basic
import qualified Haskii.Figlet.Font.Bell
import qualified Haskii.Figlet.Font.Big
import qualified Haskii.Figlet.Font.BigChief
import qualified Haskii.Figlet.Font.BigMoneyNe
import qualified Haskii.Figlet.Font.BigMoneyNw
import qualified Haskii.Figlet.Font.BigMoneySe
import qualified Haskii.Figlet.Font.BigMoneySw
import qualified Haskii.Figlet.Font.Bigfig
import qualified Haskii.Figlet.Font.Block
import qualified Haskii.Figlet.Font.Bolger
import qualified Haskii.Figlet.Font.Bright
import qualified Haskii.Figlet.Font.Brite
import qualified Haskii.Figlet.Font.Briteb
import qualified Haskii.Figlet.Font.Britebi
import qualified Haskii.Figlet.Font.Britei
import qualified Haskii.Figlet.Font.Broadway
import qualified Haskii.Figlet.Font.Bulbhead
import qualified Haskii.Figlet.Font.Calgphy2
import qualified Haskii.Figlet.Font.Caligraphy
import qualified Haskii.Figlet.Font.Caligraphy2
import qualified Haskii.Figlet.Font.Cards
import qualified Haskii.Figlet.Font.Catwalk
import qualified Haskii.Figlet.Font.Chartr
import qualified Haskii.Figlet.Font.Chartri
import qualified Haskii.Figlet.Font.Chunky
import qualified Haskii.Figlet.Font.Clb6x10
import qualified Haskii.Figlet.Font.Clb8x10
import qualified Haskii.Figlet.Font.Clb8x8
import qualified Haskii.Figlet.Font.Cli8x8
import qualified Haskii.Figlet.Font.Clr4x6
import qualified Haskii.Figlet.Font.Clr5x10
import qualified Haskii.Figlet.Font.Clr5x6
import qualified Haskii.Figlet.Font.Clr5x8
import qualified Haskii.Figlet.Font.Clr6x10
import qualified Haskii.Figlet.Font.Clr6x6
import qualified Haskii.Figlet.Font.Clr6x8
import qualified Haskii.Figlet.Font.Clr7x10
import qualified Haskii.Figlet.Font.Clr7x8
import qualified Haskii.Figlet.Font.Clr8x10
import qualified Haskii.Figlet.Font.Clr8x8
import qualified Haskii.Figlet.Font.Coinstak
import qualified Haskii.Figlet.Font.Colossal
import qualified Haskii.Figlet.Font.Computer
import qualified Haskii.Figlet.Font.Contessa
import qualified Haskii.Figlet.Font.Contrast
import qualified Haskii.Figlet.Font.Cosmic
import qualified Haskii.Figlet.Font.Cosmike
import qualified Haskii.Figlet.Font.Cour
import qualified Haskii.Figlet.Font.Courb
import qualified Haskii.Figlet.Font.Courbi
import qualified Haskii.Figlet.Font.Couri
import qualified Haskii.Figlet.Font.Crawford
import qualified Haskii.Figlet.Font.Crawford2
import qualified Haskii.Figlet.Font.Cricket
import qualified Haskii.Figlet.Font.Cursive
import qualified Haskii.Figlet.Font.Cyberlarge
import qualified Haskii.Figlet.Font.Cybermedium
import qualified Haskii.Figlet.Font.Cybersmall
import qualified Haskii.Figlet.Font.Cygnet
import qualified Haskii.Figlet.Font.DanC4
import qualified Haskii.Figlet.Font.DeltaCorpsPriest1
import qualified Haskii.Figlet.Font.Diamond
import qualified Haskii.Figlet.Font.DoSRebel
import qualified Haskii.Figlet.Font.Doh
import qualified Haskii.Figlet.Font.Doom
import qualified Haskii.Figlet.Font.DotMatrix
import qualified Haskii.Figlet.Font.Double
import qualified Haskii.Figlet.Font.DoubleShorts
import qualified Haskii.Figlet.Font.DrPepper
import qualified Haskii.Figlet.Font.EftiChess
import qualified Haskii.Figlet.Font.EftiFont
import qualified Haskii.Figlet.Font.EftiItalic
import qualified Haskii.Figlet.Font.EftiPiti
import qualified Haskii.Figlet.Font.EftiRobot
import qualified Haskii.Figlet.Font.EftiWater
import qualified Haskii.Figlet.Font.Epic
import qualified Haskii.Figlet.Font.Fender
import qualified Haskii.Figlet.Font.FireFontK
import qualified Haskii.Figlet.Font.FireFontS
import qualified Haskii.Figlet.Font.FourTops
import qualified Haskii.Figlet.Font.Fuzzy
import qualified Haskii.Figlet.Font.Goofy
import qualified Haskii.Figlet.Font.Gothic
import qualified Haskii.Figlet.Font.Graceful
import qualified Haskii.Figlet.Font.Gradient
import qualified Haskii.Figlet.Font.Graffiti
import qualified Haskii.Figlet.Font.Greek
import qualified Haskii.Figlet.Font.HeartLeft
import qualified Haskii.Figlet.Font.HeartRight
import qualified Haskii.Figlet.Font.Helv
import qualified Haskii.Figlet.Font.Helvb
import qualified Haskii.Figlet.Font.Helvbi
import qualified Haskii.Figlet.Font.Helvi
import qualified Haskii.Figlet.Font.Henry3D
import qualified Haskii.Figlet.Font.Hollywood
import qualified Haskii.Figlet.Font.Invita
import qualified Haskii.Figlet.Font.Isometric1
import qualified Haskii.Figlet.Font.Isometric2
import qualified Haskii.Figlet.Font.Isometric3
import qualified Haskii.Figlet.Font.Isometric4
import qualified Haskii.Figlet.Font.Italic
import qualified Haskii.Figlet.Font.Ivrit
import qualified Haskii.Figlet.Font.JSStickLetters
import qualified Haskii.Figlet.Font.Jacky
import qualified Haskii.Figlet.Font.Jazmine
import qualified Haskii.Figlet.Font.Jerusalem
import qualified Haskii.Figlet.Font.Jiskan16
import qualified Haskii.Figlet.Font.Katakana
import qualified Haskii.Figlet.Font.Kban
import qualified Haskii.Figlet.Font.Larry3D
import qualified Haskii.Figlet.Font.Larry3D2
import qualified Haskii.Figlet.Font.Lcd
import qualified Haskii.Figlet.Font.Lean
import qualified Haskii.Figlet.Font.Linux
import qualified Haskii.Figlet.Font.Lockergnome
import qualified Haskii.Figlet.Font.Madrid
import qualified Haskii.Figlet.Font.Marquee
import qualified Haskii.Figlet.Font.Maxfour
import qualified Haskii.Figlet.Font.Mike
import qualified Haskii.Figlet.Font.Mini
import qualified Haskii.Figlet.Font.Mirror
import qualified Haskii.Figlet.Font.Moscow
import qualified Haskii.Figlet.Font.Mshebrew210
import qualified Haskii.Figlet.Font.NScript
import qualified Haskii.Figlet.Font.NTGreek
import qualified Haskii.Figlet.Font.NVScript
import qualified Haskii.Figlet.Font.Nancyj
import qualified Haskii.Figlet.Font.NancyjFancy
import qualified Haskii.Figlet.Font.NancyjImproved
import qualified Haskii.Figlet.Font.NancyjUnderlined
import qualified Haskii.Figlet.Font.Nipples
import qualified Haskii.Figlet.Font.O8
import qualified Haskii.Figlet.Font.OS2
import qualified Haskii.Figlet.Font.Ogre
import qualified Haskii.Figlet.Font.OldBanner
import qualified Haskii.Figlet.Font.Pawp
import qualified Haskii.Figlet.Font.Peaks
import qualified Haskii.Figlet.Font.PeaksSlant
import qualified Haskii.Figlet.Font.Pebbles
import qualified Haskii.Figlet.Font.Pepper
import qualified Haskii.Figlet.Font.Puffy
import qualified Haskii.Figlet.Font.Puzzle
import qualified Haskii.Figlet.Font.Rectangles
import qualified Haskii.Figlet.Font.RedPhoenix
import qualified Haskii.Figlet.Font.Relief
import qualified Haskii.Figlet.Font.Relief2
import qualified Haskii.Figlet.Font.Rev
import qualified Haskii.Figlet.Font.Reverse
import qualified Haskii.Figlet.Font.Roman
import qualified Haskii.Figlet.Font.Rounded
import qualified Haskii.Figlet.Font.RowanCap
import qualified Haskii.Figlet.Font.Rozzo
import qualified Haskii.Figlet.Font.Runic
import qualified Haskii.Figlet.Font.Runyc
import qualified Haskii.Figlet.Font.SBlood
import qualified Haskii.Figlet.Font.SLScript
import qualified Haskii.Figlet.Font.SRelief
import qualified Haskii.Figlet.Font.Sans
import qualified Haskii.Figlet.Font.Sansb
import qualified Haskii.Figlet.Font.Sansbi
import qualified Haskii.Figlet.Font.Sansi
import qualified Haskii.Figlet.Font.SantaClara
import qualified Haskii.Figlet.Font.Sbook
import qualified Haskii.Figlet.Font.Sbookb
import qualified Haskii.Figlet.Font.Sbookbi
import qualified Haskii.Figlet.Font.Sbooki
import qualified Haskii.Figlet.Font.Script
import qualified Haskii.Figlet.Font.Serifcap
import qualified Haskii.Figlet.Font.Shadow
import qualified Haskii.Figlet.Font.Shimrod
import qualified Haskii.Figlet.Font.Short
import qualified Haskii.Figlet.Font.Slant
import qualified Haskii.Figlet.Font.SlantRelief
import qualified Haskii.Figlet.Font.Slide
import qualified Haskii.Figlet.Font.Small
import qualified Haskii.Figlet.Font.SmallIsometric1
import qualified Haskii.Figlet.Font.SmallScript
import qualified Haskii.Figlet.Font.SmallShadow
import qualified Haskii.Figlet.Font.SmallSlant
import qualified Haskii.Figlet.Font.Smisome1
import qualified Haskii.Figlet.Font.Smscript
import qualified Haskii.Figlet.Font.Smshadow
import qualified Haskii.Figlet.Font.Smslant
import qualified Haskii.Figlet.Font.Speed
import qualified Haskii.Figlet.Font.Stacey
import qualified Haskii.Figlet.Font.Stampate
import qualified Haskii.Figlet.Font.Stampatello
import qualified Haskii.Figlet.Font.Standard
import qualified Haskii.Figlet.Font.StarWars
import qualified Haskii.Figlet.Font.Stellar
import qualified Haskii.Figlet.Font.Stforek
import qualified Haskii.Figlet.Font.Stop
import qualified Haskii.Figlet.Font.Straight
import qualified Haskii.Figlet.Font.SubZero
import qualified Haskii.Figlet.Font.Swan
import qualified Haskii.Figlet.Font.Tanja
import qualified Haskii.Figlet.Font.Tengwar
import qualified Haskii.Figlet.Font.Test1
import qualified Haskii.Figlet.Font.The5x7
import qualified Haskii.Figlet.Font.The6x10
import qualified Haskii.Figlet.Font.The6x9
import qualified Haskii.Figlet.Font.TheEdge
import qualified Haskii.Figlet.Font.Thick
import qualified Haskii.Figlet.Font.Thin
import qualified Haskii.Figlet.Font.This
import qualified Haskii.Figlet.Font.ThreePoint
import qualified Haskii.Figlet.Font.Ticks
import qualified Haskii.Figlet.Font.TicksSlant
import qualified Haskii.Figlet.Font.Tiles
import qualified Haskii.Figlet.Font.Times
import qualified Haskii.Figlet.Font.TinkerToy
import qualified Haskii.Figlet.Font.Tombstone
import qualified Haskii.Figlet.Font.Trek
import qualified Haskii.Figlet.Font.Tty
import qualified Haskii.Figlet.Font.Ttyb
import qualified Haskii.Figlet.Font.Tubular
import qualified Haskii.Figlet.Font.TwoPoint
import qualified Haskii.Figlet.Font.Univers
import qualified Haskii.Figlet.Font.UsAFlag
import qualified Haskii.Figlet.Font.Utopia
import qualified Haskii.Figlet.Font.Utopiab
import qualified Haskii.Figlet.Font.Utopiabi
import qualified Haskii.Figlet.Font.Utopiai
import qualified Haskii.Figlet.Font.Wavy
import qualified Haskii.Figlet.Font.Weird
import qualified Haskii.Figlet.Font.Whimsy
import qualified Haskii.Figlet.Font.Xbrite
import qualified Haskii.Figlet.Font.Xbriteb
import qualified Haskii.Figlet.Font.Xbritebi
import qualified Haskii.Figlet.Font.Xbritei
import qualified Haskii.Figlet.Font.Xchartr
import qualified Haskii.Figlet.Font.Xchartri
import qualified Haskii.Figlet.Font.Xcour
import qualified Haskii.Figlet.Font.Xcourb
import qualified Haskii.Figlet.Font.Xcourbi
import qualified Haskii.Figlet.Font.Xcouri
import qualified Haskii.Figlet.Font.Xhelv
import qualified Haskii.Figlet.Font.Xhelvb
import qualified Haskii.Figlet.Font.Xhelvbi
import qualified Haskii.Figlet.Font.Xhelvi
import qualified Haskii.Figlet.Font.Xsans
import qualified Haskii.Figlet.Font.Xsansb
import qualified Haskii.Figlet.Font.Xsansbi
import qualified Haskii.Figlet.Font.Xsansi
import qualified Haskii.Figlet.Font.Xsbook
import qualified Haskii.Figlet.Font.Xsbookb
import qualified Haskii.Figlet.Font.Xsbookbi
import qualified Haskii.Figlet.Font.Xsbooki
import qualified Haskii.Figlet.Font.Xtimes
import qualified Haskii.Figlet.Font.Xtty
import qualified Haskii.Figlet.Font.Xttyb
data Font
  = Acrobatic |
    Alligator |
    Alligator2 |
    Alligator3 |
    Alpha |
    AmCAaA01 |
    AmCNeko |
    AmCRazor |
    AmCRazor2 |
    AmCSlash |
    AmCSlider |
    AmCThin |
    AmCTubes |
    AmCUntitled |
    Arrows |
    Avatar |
    Banner |
    Banner3 |
    Banner3D |
    Banner4 |
    Barbwire |
    Basic |
    Bell |
    Big |
    BigChief |
    BigMoneyNe |
    BigMoneyNw |
    BigMoneySe |
    BigMoneySw |
    Bigfig |
    Block |
    Bolger |
    Bright |
    Brite |
    Briteb |
    Britebi |
    Britei |
    Broadway |
    Bulbhead |
    Calgphy2 |
    Caligraphy |
    Caligraphy2 |
    Cards |
    Catwalk |
    Chartr |
    Chartri |
    Chunky |
    Clb6x10 |
    Clb8x10 |
    Clb8x8 |
    Cli8x8 |
    Clr4x6 |
    Clr5x10 |
    Clr5x6 |
    Clr5x8 |
    Clr6x10 |
    Clr6x6 |
    Clr6x8 |
    Clr7x10 |
    Clr7x8 |
    Clr8x10 |
    Clr8x8 |
    Coinstak |
    Colossal |
    Computer |
    Contessa |
    Contrast |
    Cosmic |
    Cosmike |
    Cour |
    Courb |
    Courbi |
    Couri |
    Crawford |
    Crawford2 |
    Cricket |
    Cursive |
    Cyberlarge |
    Cybermedium |
    Cybersmall |
    Cygnet |
    DanC4 |
    DeltaCorpsPriest1 |
    Diamond |
    DoSRebel |
    Doh |
    Doom |
    DotMatrix |
    Double |
    DoubleShorts |
    DrPepper |
    EftiChess |
    EftiFont |
    EftiItalic |
    EftiPiti |
    EftiRobot |
    EftiWater |
    Epic |
    Fender |
    FireFontK |
    FireFontS |
    FourTops |
    Fuzzy |
    Goofy |
    Gothic |
    Graceful |
    Gradient |
    Graffiti |
    Greek |
    HeartLeft |
    HeartRight |
    Helv |
    Helvb |
    Helvbi |
    Helvi |
    Henry3D |
    Hollywood |
    Invita |
    Isometric1 |
    Isometric2 |
    Isometric3 |
    Isometric4 |
    Italic |
    Ivrit |
    JSStickLetters |
    Jacky |
    Jazmine |
    Jerusalem |
    Jiskan16 |
    Katakana |
    Kban |
    Larry3D |
    Larry3D2 |
    Lcd |
    Lean |
    Linux |
    Lockergnome |
    Madrid |
    Marquee |
    Maxfour |
    Mike |
    Mini |
    Mirror |
    Moscow |
    Mshebrew210 |
    NScript |
    NTGreek |
    NVScript |
    Nancyj |
    NancyjFancy |
    NancyjImproved |
    NancyjUnderlined |
    Nipples |
    O8 |
    OS2 |
    Ogre |
    OldBanner |
    Pawp |
    Peaks |
    PeaksSlant |
    Pebbles |
    Pepper |
    Puffy |
    Puzzle |
    Rectangles |
    RedPhoenix |
    Relief |
    Relief2 |
    Rev |
    Reverse |
    Roman |
    Rounded |
    RowanCap |
    Rozzo |
    Runic |
    Runyc |
    SBlood |
    SLScript |
    SRelief |
    Sans |
    Sansb |
    Sansbi |
    Sansi |
    SantaClara |
    Sbook |
    Sbookb |
    Sbookbi |
    Sbooki |
    Script |
    Serifcap |
    Shadow |
    Shimrod |
    Short |
    Slant |
    SlantRelief |
    Slide |
    Small |
    SmallIsometric1 |
    SmallScript |
    SmallShadow |
    SmallSlant |
    Smisome1 |
    Smscript |
    Smshadow |
    Smslant |
    Speed |
    Stacey |
    Stampate |
    Stampatello |
    Standard |
    StarWars |
    Stellar |
    Stforek |
    Stop |
    Straight |
    SubZero |
    Swan |
    Tanja |
    Tengwar |
    Test1 |
    The5x7 |
    The6x10 |
    The6x9 |
    TheEdge |
    Thick |
    Thin |
    This |
    ThreePoint |
    Ticks |
    TicksSlant |
    Tiles |
    Times |
    TinkerToy |
    Tombstone |
    Trek |
    Tty |
    Ttyb |
    Tubular |
    TwoPoint |
    Univers |
    UsAFlag |
    Utopia |
    Utopiab |
    Utopiabi |
    Utopiai |
    Wavy |
    Weird |
    Whimsy |
    Xbrite |
    Xbriteb |
    Xbritebi |
    Xbritei |
    Xchartr |
    Xchartri |
    Xcour |
    Xcourb |
    Xcourbi |
    Xcouri |
    Xhelv |
    Xhelvb |
    Xhelvbi |
    Xhelvi |
    Xsans |
    Xsansb |
    Xsansbi |
    Xsansi |
    Xsbook |
    Xsbookb |
    Xsbookbi |
    Xsbooki |
    Xtimes |
    Xtty |
    Xttyb
  deriving (Universum.Eq,
            Universum.Ord,
            Universum.Show,
            Universum.Read)
getFLF :: Font -> Haskii.Figlet.Types.FLF
getFLF Acrobatic = Haskii.Figlet.Font.Acrobatic.getFLF
getFLF Alligator = Haskii.Figlet.Font.Alligator.getFLF
getFLF Alligator2 = Haskii.Figlet.Font.Alligator2.getFLF
getFLF Alligator3 = Haskii.Figlet.Font.Alligator3.getFLF
getFLF Alpha = Haskii.Figlet.Font.Alpha.getFLF
getFLF AmCAaA01 = Haskii.Figlet.Font.AmCAaA01.getFLF
getFLF AmCNeko = Haskii.Figlet.Font.AmCNeko.getFLF
getFLF AmCRazor = Haskii.Figlet.Font.AmCRazor.getFLF
getFLF AmCRazor2 = Haskii.Figlet.Font.AmCRazor2.getFLF
getFLF AmCSlash = Haskii.Figlet.Font.AmCSlash.getFLF
getFLF AmCSlider = Haskii.Figlet.Font.AmCSlider.getFLF
getFLF AmCThin = Haskii.Figlet.Font.AmCThin.getFLF
getFLF AmCTubes = Haskii.Figlet.Font.AmCTubes.getFLF
getFLF AmCUntitled = Haskii.Figlet.Font.AmCUntitled.getFLF
getFLF Arrows = Haskii.Figlet.Font.Arrows.getFLF
getFLF Avatar = Haskii.Figlet.Font.Avatar.getFLF
getFLF Banner = Haskii.Figlet.Font.Banner.getFLF
getFLF Banner3 = Haskii.Figlet.Font.Banner3.getFLF
getFLF Banner3D = Haskii.Figlet.Font.Banner3D.getFLF
getFLF Banner4 = Haskii.Figlet.Font.Banner4.getFLF
getFLF Barbwire = Haskii.Figlet.Font.Barbwire.getFLF
getFLF Basic = Haskii.Figlet.Font.Basic.getFLF
getFLF Bell = Haskii.Figlet.Font.Bell.getFLF
getFLF Big = Haskii.Figlet.Font.Big.getFLF
getFLF BigChief = Haskii.Figlet.Font.BigChief.getFLF
getFLF BigMoneyNe = Haskii.Figlet.Font.BigMoneyNe.getFLF
getFLF BigMoneyNw = Haskii.Figlet.Font.BigMoneyNw.getFLF
getFLF BigMoneySe = Haskii.Figlet.Font.BigMoneySe.getFLF
getFLF BigMoneySw = Haskii.Figlet.Font.BigMoneySw.getFLF
getFLF Bigfig = Haskii.Figlet.Font.Bigfig.getFLF
getFLF Block = Haskii.Figlet.Font.Block.getFLF
getFLF Bolger = Haskii.Figlet.Font.Bolger.getFLF
getFLF Bright = Haskii.Figlet.Font.Bright.getFLF
getFLF Brite = Haskii.Figlet.Font.Brite.getFLF
getFLF Briteb = Haskii.Figlet.Font.Briteb.getFLF
getFLF Britebi = Haskii.Figlet.Font.Britebi.getFLF
getFLF Britei = Haskii.Figlet.Font.Britei.getFLF
getFLF Broadway = Haskii.Figlet.Font.Broadway.getFLF
getFLF Bulbhead = Haskii.Figlet.Font.Bulbhead.getFLF
getFLF Calgphy2 = Haskii.Figlet.Font.Calgphy2.getFLF
getFLF Caligraphy = Haskii.Figlet.Font.Caligraphy.getFLF
getFLF Caligraphy2 = Haskii.Figlet.Font.Caligraphy2.getFLF
getFLF Cards = Haskii.Figlet.Font.Cards.getFLF
getFLF Catwalk = Haskii.Figlet.Font.Catwalk.getFLF
getFLF Chartr = Haskii.Figlet.Font.Chartr.getFLF
getFLF Chartri = Haskii.Figlet.Font.Chartri.getFLF
getFLF Chunky = Haskii.Figlet.Font.Chunky.getFLF
getFLF Clb6x10 = Haskii.Figlet.Font.Clb6x10.getFLF
getFLF Clb8x10 = Haskii.Figlet.Font.Clb8x10.getFLF
getFLF Clb8x8 = Haskii.Figlet.Font.Clb8x8.getFLF
getFLF Cli8x8 = Haskii.Figlet.Font.Cli8x8.getFLF
getFLF Clr4x6 = Haskii.Figlet.Font.Clr4x6.getFLF
getFLF Clr5x10 = Haskii.Figlet.Font.Clr5x10.getFLF
getFLF Clr5x6 = Haskii.Figlet.Font.Clr5x6.getFLF
getFLF Clr5x8 = Haskii.Figlet.Font.Clr5x8.getFLF
getFLF Clr6x10 = Haskii.Figlet.Font.Clr6x10.getFLF
getFLF Clr6x6 = Haskii.Figlet.Font.Clr6x6.getFLF
getFLF Clr6x8 = Haskii.Figlet.Font.Clr6x8.getFLF
getFLF Clr7x10 = Haskii.Figlet.Font.Clr7x10.getFLF
getFLF Clr7x8 = Haskii.Figlet.Font.Clr7x8.getFLF
getFLF Clr8x10 = Haskii.Figlet.Font.Clr8x10.getFLF
getFLF Clr8x8 = Haskii.Figlet.Font.Clr8x8.getFLF
getFLF Coinstak = Haskii.Figlet.Font.Coinstak.getFLF
getFLF Colossal = Haskii.Figlet.Font.Colossal.getFLF
getFLF Computer = Haskii.Figlet.Font.Computer.getFLF
getFLF Contessa = Haskii.Figlet.Font.Contessa.getFLF
getFLF Contrast = Haskii.Figlet.Font.Contrast.getFLF
getFLF Cosmic = Haskii.Figlet.Font.Cosmic.getFLF
getFLF Cosmike = Haskii.Figlet.Font.Cosmike.getFLF
getFLF Cour = Haskii.Figlet.Font.Cour.getFLF
getFLF Courb = Haskii.Figlet.Font.Courb.getFLF
getFLF Courbi = Haskii.Figlet.Font.Courbi.getFLF
getFLF Couri = Haskii.Figlet.Font.Couri.getFLF
getFLF Crawford = Haskii.Figlet.Font.Crawford.getFLF
getFLF Crawford2 = Haskii.Figlet.Font.Crawford2.getFLF
getFLF Cricket = Haskii.Figlet.Font.Cricket.getFLF
getFLF Cursive = Haskii.Figlet.Font.Cursive.getFLF
getFLF Cyberlarge = Haskii.Figlet.Font.Cyberlarge.getFLF
getFLF Cybermedium = Haskii.Figlet.Font.Cybermedium.getFLF
getFLF Cybersmall = Haskii.Figlet.Font.Cybersmall.getFLF
getFLF Cygnet = Haskii.Figlet.Font.Cygnet.getFLF
getFLF DanC4 = Haskii.Figlet.Font.DanC4.getFLF
getFLF DeltaCorpsPriest1
  = Haskii.Figlet.Font.DeltaCorpsPriest1.getFLF
getFLF Diamond = Haskii.Figlet.Font.Diamond.getFLF
getFLF DoSRebel = Haskii.Figlet.Font.DoSRebel.getFLF
getFLF Doh = Haskii.Figlet.Font.Doh.getFLF
getFLF Doom = Haskii.Figlet.Font.Doom.getFLF
getFLF DotMatrix = Haskii.Figlet.Font.DotMatrix.getFLF
getFLF Double = Haskii.Figlet.Font.Double.getFLF
getFLF DoubleShorts = Haskii.Figlet.Font.DoubleShorts.getFLF
getFLF DrPepper = Haskii.Figlet.Font.DrPepper.getFLF
getFLF EftiChess = Haskii.Figlet.Font.EftiChess.getFLF
getFLF EftiFont = Haskii.Figlet.Font.EftiFont.getFLF
getFLF EftiItalic = Haskii.Figlet.Font.EftiItalic.getFLF
getFLF EftiPiti = Haskii.Figlet.Font.EftiPiti.getFLF
getFLF EftiRobot = Haskii.Figlet.Font.EftiRobot.getFLF
getFLF EftiWater = Haskii.Figlet.Font.EftiWater.getFLF
getFLF Epic = Haskii.Figlet.Font.Epic.getFLF
getFLF Fender = Haskii.Figlet.Font.Fender.getFLF
getFLF FireFontK = Haskii.Figlet.Font.FireFontK.getFLF
getFLF FireFontS = Haskii.Figlet.Font.FireFontS.getFLF
getFLF FourTops = Haskii.Figlet.Font.FourTops.getFLF
getFLF Fuzzy = Haskii.Figlet.Font.Fuzzy.getFLF
getFLF Goofy = Haskii.Figlet.Font.Goofy.getFLF
getFLF Gothic = Haskii.Figlet.Font.Gothic.getFLF
getFLF Graceful = Haskii.Figlet.Font.Graceful.getFLF
getFLF Gradient = Haskii.Figlet.Font.Gradient.getFLF
getFLF Graffiti = Haskii.Figlet.Font.Graffiti.getFLF
getFLF Greek = Haskii.Figlet.Font.Greek.getFLF
getFLF HeartLeft = Haskii.Figlet.Font.HeartLeft.getFLF
getFLF HeartRight = Haskii.Figlet.Font.HeartRight.getFLF
getFLF Helv = Haskii.Figlet.Font.Helv.getFLF
getFLF Helvb = Haskii.Figlet.Font.Helvb.getFLF
getFLF Helvbi = Haskii.Figlet.Font.Helvbi.getFLF
getFLF Helvi = Haskii.Figlet.Font.Helvi.getFLF
getFLF Henry3D = Haskii.Figlet.Font.Henry3D.getFLF
getFLF Hollywood = Haskii.Figlet.Font.Hollywood.getFLF
getFLF Invita = Haskii.Figlet.Font.Invita.getFLF
getFLF Isometric1 = Haskii.Figlet.Font.Isometric1.getFLF
getFLF Isometric2 = Haskii.Figlet.Font.Isometric2.getFLF
getFLF Isometric3 = Haskii.Figlet.Font.Isometric3.getFLF
getFLF Isometric4 = Haskii.Figlet.Font.Isometric4.getFLF
getFLF Italic = Haskii.Figlet.Font.Italic.getFLF
getFLF Ivrit = Haskii.Figlet.Font.Ivrit.getFLF
getFLF JSStickLetters = Haskii.Figlet.Font.JSStickLetters.getFLF
getFLF Jacky = Haskii.Figlet.Font.Jacky.getFLF
getFLF Jazmine = Haskii.Figlet.Font.Jazmine.getFLF
getFLF Jerusalem = Haskii.Figlet.Font.Jerusalem.getFLF
getFLF Jiskan16 = Haskii.Figlet.Font.Jiskan16.getFLF
getFLF Katakana = Haskii.Figlet.Font.Katakana.getFLF
getFLF Kban = Haskii.Figlet.Font.Kban.getFLF
getFLF Larry3D = Haskii.Figlet.Font.Larry3D.getFLF
getFLF Larry3D2 = Haskii.Figlet.Font.Larry3D2.getFLF
getFLF Lcd = Haskii.Figlet.Font.Lcd.getFLF
getFLF Lean = Haskii.Figlet.Font.Lean.getFLF
getFLF Linux = Haskii.Figlet.Font.Linux.getFLF
getFLF Lockergnome = Haskii.Figlet.Font.Lockergnome.getFLF
getFLF Madrid = Haskii.Figlet.Font.Madrid.getFLF
getFLF Marquee = Haskii.Figlet.Font.Marquee.getFLF
getFLF Maxfour = Haskii.Figlet.Font.Maxfour.getFLF
getFLF Mike = Haskii.Figlet.Font.Mike.getFLF
getFLF Mini = Haskii.Figlet.Font.Mini.getFLF
getFLF Mirror = Haskii.Figlet.Font.Mirror.getFLF
getFLF Moscow = Haskii.Figlet.Font.Moscow.getFLF
getFLF Mshebrew210 = Haskii.Figlet.Font.Mshebrew210.getFLF
getFLF NScript = Haskii.Figlet.Font.NScript.getFLF
getFLF NTGreek = Haskii.Figlet.Font.NTGreek.getFLF
getFLF NVScript = Haskii.Figlet.Font.NVScript.getFLF
getFLF Nancyj = Haskii.Figlet.Font.Nancyj.getFLF
getFLF NancyjFancy = Haskii.Figlet.Font.NancyjFancy.getFLF
getFLF NancyjImproved = Haskii.Figlet.Font.NancyjImproved.getFLF
getFLF NancyjUnderlined
  = Haskii.Figlet.Font.NancyjUnderlined.getFLF
getFLF Nipples = Haskii.Figlet.Font.Nipples.getFLF
getFLF O8 = Haskii.Figlet.Font.O8.getFLF
getFLF OS2 = Haskii.Figlet.Font.OS2.getFLF
getFLF Ogre = Haskii.Figlet.Font.Ogre.getFLF
getFLF OldBanner = Haskii.Figlet.Font.OldBanner.getFLF
getFLF Pawp = Haskii.Figlet.Font.Pawp.getFLF
getFLF Peaks = Haskii.Figlet.Font.Peaks.getFLF
getFLF PeaksSlant = Haskii.Figlet.Font.PeaksSlant.getFLF
getFLF Pebbles = Haskii.Figlet.Font.Pebbles.getFLF
getFLF Pepper = Haskii.Figlet.Font.Pepper.getFLF
getFLF Puffy = Haskii.Figlet.Font.Puffy.getFLF
getFLF Puzzle = Haskii.Figlet.Font.Puzzle.getFLF
getFLF Rectangles = Haskii.Figlet.Font.Rectangles.getFLF
getFLF RedPhoenix = Haskii.Figlet.Font.RedPhoenix.getFLF
getFLF Relief = Haskii.Figlet.Font.Relief.getFLF
getFLF Relief2 = Haskii.Figlet.Font.Relief2.getFLF
getFLF Rev = Haskii.Figlet.Font.Rev.getFLF
getFLF Reverse = Haskii.Figlet.Font.Reverse.getFLF
getFLF Roman = Haskii.Figlet.Font.Roman.getFLF
getFLF Rounded = Haskii.Figlet.Font.Rounded.getFLF
getFLF RowanCap = Haskii.Figlet.Font.RowanCap.getFLF
getFLF Rozzo = Haskii.Figlet.Font.Rozzo.getFLF
getFLF Runic = Haskii.Figlet.Font.Runic.getFLF
getFLF Runyc = Haskii.Figlet.Font.Runyc.getFLF
getFLF SBlood = Haskii.Figlet.Font.SBlood.getFLF
getFLF SLScript = Haskii.Figlet.Font.SLScript.getFLF
getFLF SRelief = Haskii.Figlet.Font.SRelief.getFLF
getFLF Sans = Haskii.Figlet.Font.Sans.getFLF
getFLF Sansb = Haskii.Figlet.Font.Sansb.getFLF
getFLF Sansbi = Haskii.Figlet.Font.Sansbi.getFLF
getFLF Sansi = Haskii.Figlet.Font.Sansi.getFLF
getFLF SantaClara = Haskii.Figlet.Font.SantaClara.getFLF
getFLF Sbook = Haskii.Figlet.Font.Sbook.getFLF
getFLF Sbookb = Haskii.Figlet.Font.Sbookb.getFLF
getFLF Sbookbi = Haskii.Figlet.Font.Sbookbi.getFLF
getFLF Sbooki = Haskii.Figlet.Font.Sbooki.getFLF
getFLF Script = Haskii.Figlet.Font.Script.getFLF
getFLF Serifcap = Haskii.Figlet.Font.Serifcap.getFLF
getFLF Shadow = Haskii.Figlet.Font.Shadow.getFLF
getFLF Shimrod = Haskii.Figlet.Font.Shimrod.getFLF
getFLF Short = Haskii.Figlet.Font.Short.getFLF
getFLF Slant = Haskii.Figlet.Font.Slant.getFLF
getFLF SlantRelief = Haskii.Figlet.Font.SlantRelief.getFLF
getFLF Slide = Haskii.Figlet.Font.Slide.getFLF
getFLF Small = Haskii.Figlet.Font.Small.getFLF
getFLF SmallIsometric1 = Haskii.Figlet.Font.SmallIsometric1.getFLF
getFLF SmallScript = Haskii.Figlet.Font.SmallScript.getFLF
getFLF SmallShadow = Haskii.Figlet.Font.SmallShadow.getFLF
getFLF SmallSlant = Haskii.Figlet.Font.SmallSlant.getFLF
getFLF Smisome1 = Haskii.Figlet.Font.Smisome1.getFLF
getFLF Smscript = Haskii.Figlet.Font.Smscript.getFLF
getFLF Smshadow = Haskii.Figlet.Font.Smshadow.getFLF
getFLF Smslant = Haskii.Figlet.Font.Smslant.getFLF
getFLF Speed = Haskii.Figlet.Font.Speed.getFLF
getFLF Stacey = Haskii.Figlet.Font.Stacey.getFLF
getFLF Stampate = Haskii.Figlet.Font.Stampate.getFLF
getFLF Stampatello = Haskii.Figlet.Font.Stampatello.getFLF
getFLF Standard = Haskii.Figlet.Font.Standard.getFLF
getFLF StarWars = Haskii.Figlet.Font.StarWars.getFLF
getFLF Stellar = Haskii.Figlet.Font.Stellar.getFLF
getFLF Stforek = Haskii.Figlet.Font.Stforek.getFLF
getFLF Stop = Haskii.Figlet.Font.Stop.getFLF
getFLF Straight = Haskii.Figlet.Font.Straight.getFLF
getFLF SubZero = Haskii.Figlet.Font.SubZero.getFLF
getFLF Swan = Haskii.Figlet.Font.Swan.getFLF
getFLF Tanja = Haskii.Figlet.Font.Tanja.getFLF
getFLF Tengwar = Haskii.Figlet.Font.Tengwar.getFLF
getFLF Test1 = Haskii.Figlet.Font.Test1.getFLF
getFLF The5x7 = Haskii.Figlet.Font.The5x7.getFLF
getFLF The6x10 = Haskii.Figlet.Font.The6x10.getFLF
getFLF The6x9 = Haskii.Figlet.Font.The6x9.getFLF
getFLF TheEdge = Haskii.Figlet.Font.TheEdge.getFLF
getFLF Thick = Haskii.Figlet.Font.Thick.getFLF
getFLF Thin = Haskii.Figlet.Font.Thin.getFLF
getFLF This = Haskii.Figlet.Font.This.getFLF
getFLF ThreePoint = Haskii.Figlet.Font.ThreePoint.getFLF
getFLF Ticks = Haskii.Figlet.Font.Ticks.getFLF
getFLF TicksSlant = Haskii.Figlet.Font.TicksSlant.getFLF
getFLF Tiles = Haskii.Figlet.Font.Tiles.getFLF
getFLF Times = Haskii.Figlet.Font.Times.getFLF
getFLF TinkerToy = Haskii.Figlet.Font.TinkerToy.getFLF
getFLF Tombstone = Haskii.Figlet.Font.Tombstone.getFLF
getFLF Trek = Haskii.Figlet.Font.Trek.getFLF
getFLF Tty = Haskii.Figlet.Font.Tty.getFLF
getFLF Ttyb = Haskii.Figlet.Font.Ttyb.getFLF
getFLF Tubular = Haskii.Figlet.Font.Tubular.getFLF
getFLF TwoPoint = Haskii.Figlet.Font.TwoPoint.getFLF
getFLF Univers = Haskii.Figlet.Font.Univers.getFLF
getFLF UsAFlag = Haskii.Figlet.Font.UsAFlag.getFLF
getFLF Utopia = Haskii.Figlet.Font.Utopia.getFLF
getFLF Utopiab = Haskii.Figlet.Font.Utopiab.getFLF
getFLF Utopiabi = Haskii.Figlet.Font.Utopiabi.getFLF
getFLF Utopiai = Haskii.Figlet.Font.Utopiai.getFLF
getFLF Wavy = Haskii.Figlet.Font.Wavy.getFLF
getFLF Weird = Haskii.Figlet.Font.Weird.getFLF
getFLF Whimsy = Haskii.Figlet.Font.Whimsy.getFLF
getFLF Xbrite = Haskii.Figlet.Font.Xbrite.getFLF
getFLF Xbriteb = Haskii.Figlet.Font.Xbriteb.getFLF
getFLF Xbritebi = Haskii.Figlet.Font.Xbritebi.getFLF
getFLF Xbritei = Haskii.Figlet.Font.Xbritei.getFLF
getFLF Xchartr = Haskii.Figlet.Font.Xchartr.getFLF
getFLF Xchartri = Haskii.Figlet.Font.Xchartri.getFLF
getFLF Xcour = Haskii.Figlet.Font.Xcour.getFLF
getFLF Xcourb = Haskii.Figlet.Font.Xcourb.getFLF
getFLF Xcourbi = Haskii.Figlet.Font.Xcourbi.getFLF
getFLF Xcouri = Haskii.Figlet.Font.Xcouri.getFLF
getFLF Xhelv = Haskii.Figlet.Font.Xhelv.getFLF
getFLF Xhelvb = Haskii.Figlet.Font.Xhelvb.getFLF
getFLF Xhelvbi = Haskii.Figlet.Font.Xhelvbi.getFLF
getFLF Xhelvi = Haskii.Figlet.Font.Xhelvi.getFLF
getFLF Xsans = Haskii.Figlet.Font.Xsans.getFLF
getFLF Xsansb = Haskii.Figlet.Font.Xsansb.getFLF
getFLF Xsansbi = Haskii.Figlet.Font.Xsansbi.getFLF
getFLF Xsansi = Haskii.Figlet.Font.Xsansi.getFLF
getFLF Xsbook = Haskii.Figlet.Font.Xsbook.getFLF
getFLF Xsbookb = Haskii.Figlet.Font.Xsbookb.getFLF
getFLF Xsbookbi = Haskii.Figlet.Font.Xsbookbi.getFLF
getFLF Xsbooki = Haskii.Figlet.Font.Xsbooki.getFLF
getFLF Xtimes = Haskii.Figlet.Font.Xtimes.getFLF
getFLF Xtty = Haskii.Figlet.Font.Xtty.getFLF
getFLF Xttyb = Haskii.Figlet.Font.Xttyb.getFLF